name: portfolio-vs

services:
  kleidung-service:
    build:
      context: ./kleidung-service
      dockerfile: Dockerfile
    container_name: kleidung-service
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 1234
      NODE_ENV: production
      MQTT_BROKER: mqtt://host.docker.internal:1883
      MQTT_USERNAME: mosquitto
      MQTT_PASSWORD: mosquitto
    ports:
      - "1234:1234"
    volumes:
      - ./kleidung-service/db_ks.sqlite:/app/db_ks.sqlite
    restart: unless-stopped

  wasch-service:
    build:
      context: ./wasch-service
      dockerfile: Dockerfile
    container_name: wasch-service
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 4321
      NODE_ENV: production
      MQTT_BROKER: mqtt://host.docker.internal:1883
      MQTT_USERNAME: mosquitto
      MQTT_PASSWORD: mosquitto
    ports:
      - "4321:4321"
    volumes:
      - ./wasch-service/db_ws.sqlite:/app/db_ws.sqlite
    restart: unless-stopped
